# Generated by Django 6.0.5 on 2026-06-04 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('club_type', models.CharField(choices=[('DRIVER', 'Driver'), ('WOOD', 'Wood'), ('HYBRID', 'Hybrid'), ('IRON', 'Iron'), ('WEDGE', 'Wedge'), ('PUTTER', 'Putter')], max_length=20)),
                ('average_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('shortest_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('longest_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['club_type', 'name'],
            },
        ),
    ]
