# Generated by Django 6.0.5 on 2026-06-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_shotsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carry_distance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('total_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ball_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('club_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('launch_angle', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spin_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='clubs.club')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='clubs.shotsession')),
            ],
            options={
                'ordering': ['club', 'created_at'],
            },
        ),
    ]
